### ISSUE TITLE
Empty Template Pool

### ISSUE THREAD

**Issue by diablo050189** [frqnny/mostructures-forge#2]
This error is spamming my server logs.

Forge Version: 36.2.0
Mo'Structures Version: Forge 1.2.0-1.16.5 

****************** Blame Report Template Pool1.16.5-3.2.5-forge ******************

 Empty template pool found from : mostructures:tavern/trees
 The path represented by this is:  data/mostructures/worldgen/template_pool/tavern/trees
 The structure piece with a Jigsaw Block that is targeting an empty pool is: mostructures:tavern/tavern_3
 Most common cause is that there is a typo in this path to the template pool which then points to a non-existent pool.
 Please let the mod author know about this so they can double check the path to make sure it is correct.

[10:14:14] [Worker-Main-1/WARN] [minecraft/JigsawManager]: Empty or none existent pool: mostructures:tavern/trees
[10:14:14] [Worker-Main-1/WARN] [minecraft/JigsawManager]: Empty or none existent pool: mostructures:tavern/trees
[10:14:14] [Worker-Main-1/WARN] [minecraft/JigsawManager]: Empty or none existent pool: mostructures:tavern/trees

**Comment by frqnny** [comment]
Take out blame and you won’t have to deal with it

**Comment by diablo050189** [comment]
Just ignoring the problem doesn't fix it

**Comment by diablo050189** [comment]
Alright, well removing your mod was a good enough solution for me. It solves the problem.

**Comment by frqnny** [comment]
bet!

**Comment by TelepathicGrunt** [comment]
@diablo050189, Blame is for diagnosing issues. It sounds like you have Blame on 24/7 which is not the intended purpose of the mod. Please remove Blame (my mod) when not trying to debug a crash or why some worldgen is being funky. This specific blame report is just saying there was an attempt to spawn a tree piece in the tavern but couldn’t. It won’t really affect your game or worldgen. And spamming logs isn’t a concern as Blame isn’t suppose to be on all the time. It is design to print the maximum amount of info it can find so me, other modders, and modpack makers can see all problems right away without needing people to configure blame.

**Comment by diablo050189** [comment]
I am setting up a forge server and experienced 3 server crashes within a few minutes of starting up the server. I added blame to figure out what the issue was and found 4 mods including this one that were throwing up errors and reported them all. One just forgot to remove debug code, 2 have yet to respond and this one just told me to remove blame. Removing blame isn't going to help me figure out why it keeps crashing randomly, that's why I added blame.

**Comment by TelepathicGrunt** [comment]
Understandable.. If you are still having issues with the crashes and blame isn't helping, you can open an issue report on my Blame github with the latest.log of the current unknown crash you are stuck on and I can try and help you out. Maybe I can even check if it is something Blame can gather more info on in the future

**Comment by frqnny** [comment]
if you told me it was a crash and not just something i know for a fact to not show up frequently at all maybe we could have helped you earlier ._. if u experience confusing crashes feel free to ask on any modded discord about it as rhere are tons of people who will help you. but ok, “log spam”
