### ISSUE TITLE
Pillaged factory not spewing pillagers

### ISSUE THREAD

**Issue by GauntAndreX8** [frqnny/mostructures-forge#3]
The pillaged factory is not spawning any pillagers and no raveger as well

**Comment by frqnny** [comment]
this is so weird adn always happens in forge 

please have more info or I won't try to diagnose this

**Comment by GauntAndreX8** [comment]
Well there’s no pillagers around or in the area and no race get spawned in the building loots and spider spawners still generate

**Comment by frqnny** [comment]
i meant logs, mods installed, did you even check the difficulty?...

**Comment by GauntAndreX8** [comment]
Yes i was on normal

**Comment by GauntAndreX8** [comment]
I can check what mods I also have

**Comment by GauntAndreX8** [comment]
ok here it is all mods i have currently

**Comment by GauntAndreX8** [comment]
Mod List: 
		StructuresPlusEnd.jar                             |Structure plus ii             |structure_plus_ii             |1.0.0               |DONE      |Manifest: NOSIGNATURE
		BetterDungeons-1.16.4-1.2.jar                     |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2          |DONE      |Manifest: NOSIGNATURE
		NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |DONE      |Manifest: NOSIGNATURE
		Mob-Battle-Mod-1.16.5.jar                         |Mob Battle Mod                |mobbattle                     |1.16.2-2.3.4        |DONE      |Manifest: NOSIGNATURE
		bigbrain-1.2.4.jar                                |Big Brain                     |bigbrain                      |1.2.4               |DONE      |Manifest: NOSIGNATURE
		infernal-expansion-2.2.0.jar                      |Infernal Expansion            |infernalexp                   |2.2.0               |DONE      |Manifest: NOSIGNATURE
		BetterF3-1.1.3-forge-1.16.5.jar                   |BetterF3 Forge                |betterf3forge                 |1.1.3               |DONE      |Manifest: NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |DONE      |Manifest: NOSIGNATURE
		strawgolem-1.16-1.9.jar                           |Straw Golem                   |strawgolem                    |1.16-1.9            |DONE      |Manifest: NOSIGNATURE
		looot-1.16.4-1.0.0.3.jar                          |Looot                         |looot                         |1.0.0.3             |DONE      |Manifest: NOSIGNATURE
		hourglass-1.16.5-1.2.0.0.jar                      |Hourglass                     |hourglass                     |1.16.5-1.2.0.0      |DONE      |Manifest: NOSIGNATURE
		InsaneLib-1.2.1-mc1.16.5.jar                      |InsaneLib                     |insanelib                     |1.2.1-mc1.16.5      |DONE      |Manifest: NOSIGNATURE
		villagernames_1.16.5-3.3.jar                      |Villager Names                |villagernames                 |3.3                 |DONE      |Manifest: NOSIGNATURE
		TerraForged-1.16.5-0.2.15.jar                     |TerraForged                   |terraforged                   |0.2.15              |DONE      |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		configurableextramobdrops_1.16.5-1.6.jar          |Configurable Extra Mob Drops  |configurableextramobdrops     |1.6                 |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.6.0.jar                          |Placebo                       |placebo                       |4.6.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.0-1.16.5.jar                          |Citadel                       |citadel                       |1.8.0               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.0              |DONE      |Manifest: NOSIGNATURE
		farmersdelightintegrations-1.16.5-1.2.jar         |Farmer's Delight Compats      |farmersdelightintegrations    |1.16.5-1.2          |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.2.28.jar                |Bookshelf                     |bookshelf                     |10.2.28             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Tips-1.16.5-4.0.10.jar                            |Tips                          |tips                          |4.0.10              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.16.5.1.2.4.jar                   |Guard Villagers               |guardvillagers                |1.2.4               |DONE      |Manifest: NOSIGNATURE
		ShretNether+-+Release+-1.3.2.jar                  |Shret Nether                  |shretnether                   |1.0                 |DONE      |Manifest: NOSIGNATURE
		ProgressiveBosses-3.3.2-mc1.16.5.jar              |Progressive Bosses            |progressivebosses             |3.3.2               |DONE      |Manifest: NOSIGNATURE
		SnowRealMagic-1.16.4-2.6.1.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.6.1               |DONE      |Manifest: NOSIGNATURE
		FpsReducer-forge-1.23-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.23-mc1.16.5       |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |DONE      |Manifest: NOSIGNATURE
		dynmus-1.3.1.jar                                  |Dynamic Music                 |dynmus                        |1.3.1               |DONE      |Manifest: NOSIGNATURE
		Uncrafter-1.16.5-0.4.0.jar                        |Uncrafter                     |uncrafter                     |1.16.5-0.4.0        |DONE      |Manifest: NOSIGNATURE
		mobtotems-1.0.0.jar                               |More Totems                   |moretotems                    |1.0.0               |DONE      |Manifest: NOSIGNATURE
		mineralchance_1.16.5-1.6.jar                      |Mineral Chance                |mineralchance                 |1.6                 |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.16.1.jar                 |Supplementaries               |supplementaries               |1.16.5-0.16.0       |DONE      |Manifest: NOSIGNATURE
		konkrete_1.1.6_MC_1.16.2-1.16.5.jar               |Konkrete                      |konkrete                      |1.1.6               |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |Manifest: NOSIGNATURE
		AdvancementPlaques-1.16.5-1.4.0.jar               |Advancement Plaques           |advancementplaques            |1.4.0               |DONE      |Manifest: NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.6.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.6        |DONE      |Manifest: NOSIGNATURE
		cleancut-mc1.16-2.2-forge.jar                     |Clean Cut                     |cleancut                      |2.2                 |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.2.4+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.2.4+1.16.5        |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.4.jar              |More Villagers                |morevillagers                 |1.5.4               |DONE      |Manifest: NOSIGNATURE
		locallooks-1.0.0-1.16.5.jar                       |Local Looks                   |locallooks                    |1.0.0               |DONE      |Manifest: NOSIGNATURE
		ender-chested-1.16.4-1.0.2.jar                    |Ender Chested                 |ender_chest_horses            |1.0.2               |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v3.1.9_mc1.16.5.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		EndRemastered-R36.jar                             |End Remastered 3.6            |endrem                        |1.16.3              |DONE      |Manifest: NOSIGNATURE
		CMDCam_v1.5.22_mc1.16.5.jar                       |CMDCam                        |cmdcam                        |1.5.0               |DONE      |Manifest: NOSIGNATURE
		toughnessbar-6.1.jar                              |Toughness Bar                 |toughnessbar                  |6.1                 |DONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |DONE      |Manifest: NOSIGNATURE
		skinned_lanterns-1.16.5-1.3.1.jar                 |Skinned Lanterns              |skinnedlanterns               |1.16.5-1.3.1        |DONE      |Manifest: NOSIGNATURE
		rare-ice-0.2.2.jar                                |Rare Ice                      |rare-ice                      |version             |DONE      |Manifest: NOSIGNATURE
		ElenaiDodge2-1.16.X-1.1.0.jar                     |Elenai Dodge 2                |elenaidodge2                  |1.1.0               |DONE      |Manifest: NOSIGNATURE
		StumbleUponCampsites.jar                          |StumbleUponCamps              |stumbleuponcamps              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |DONE      |Manifest: NOSIGNATURE
		EyesInTheDarkness-1.16.5-1.0.3.jar                |Eyes in the Darkness          |eyesinthedarkness             |1.0.3               |DONE      |Manifest: NOSIGNATURE
		darkerdepths-1.16.5-1.1.1.jar                     |Darker Depths                 |darkerdepths                  |1.16.5-1.1.1}       |DONE      |Manifest: NOSIGNATURE
		spark-forge.jar                                   |spark                         |spark                         |1.6.0               |DONE      |Manifest: NOSIGNATURE
		mostructures-forge-1.2.0-1.16.5.jar               |Mo' Structures                |mostructures                  |1.2.0-1.16.5        |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		omnis-1.16.5-1.1.2.3.jar                          |Omnis                         |omnis                         |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		omnis_backpacks-1.2.1.jar                         |Omnis Backpacks               |omnis_backpacks               |1.2.1               |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-2.64.jar                        |Collective                    |collective                    |2.64                |DONE      |Manifest: NOSIGNATURE
		betterbiomeblend-1.16.4-1.2.9-forge.jar           |Better Biome Blend            |betterbiomeblend              |1.16.4-1.2.9-forge  |DONE      |Manifest: NOSIGNATURE
		Snow_Pig-1.16.5-2.3.1.jar                         |Snow Pig                      |snowpig                       |1.16.5-2.3.1        |DONE      |Manifest: NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		passiveshield_1.16.5-1.4.jar                      |Passive Shield                |passiveshield                 |1.4                 |DONE      |Manifest: NOSIGNATURE
		sapience-1.16.5-1.1.2.jar                         |Sapience                      |sapience                      |1.1.2               |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |DONE      |Manifest: NOSIGNATURE
		enchantwithmob-1.16.5-1.4.6.jar                   |Enchant With Mob              |enchantwithmob                |1.16.5-1.4.6        |DONE      |Manifest: NOSIGNATURE
		GameMenuModOption-1.16.4-1.8.jar                  |Game Menu Mod Option          |gamemenumodoption             |1.8                 |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		veinmining-forge-1.16.5-0.12.jar                  |Vein Mining                   |veinmining                    |1.16.5-0.12         |DONE      |Manifest: NOSIGNATURE
		stables-1.16.5-1.0.1.jar                          |Stables                       |stables                       |1.16.5-1.0.1        |DONE      |Manifest: NOSIGNATURE
		DarkPaintings-1.16.5-6.0.3.jar                    |DarkPaintings                 |darkpaintings                 |6.0.3               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BetterAdvancements-1.16.5-0.1.1.115.jar           |Better Advancements           |betteradvancements            |0.1.1.115           |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.16.5-3.5.2.jar                             |Kiwi                          |kiwi                          |3.5.2               |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |DONE      |Manifest: NOSIGNATURE
		Cursed-1.16.5-7.0.1.jar                           |Cursed                        |cursed                        |7.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TheComfortZone-1.16.5-1.0.2-b.jar                 |The Comfort Zone              |thecomfortzone                |1.16.5-1.0.2-b      |DONE      |Manifest: NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |DONE      |Manifest: NOSIGNATURE
		Shrines-1.16.5-2.0.0-SNAPSHOT-10.jar              |Shrines                       |shrines                       |1.16.5-2.0.0-SNAPSHO|DONE      |Manifest: NOSIGNATURE
		treeharvester_1.16.5-3.2.jar                      |Tree Harvester                |treeharvester                 |3.2                 |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v1.0.3-1.16.5.jar                       |Easy Magic                    |easymagic                     |1.0.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.16.5-7.7.1.121.jar                          |Just Enough Items             |jei                           |7.7.1.121           |DONE      |Manifest: NOSIGNATURE
		AttributeFix-1.16.5-10.1.2.jar                    |AttributeFix                  |attributefix                  |10.1.2              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		Fruitful-1.16.5-2.1.0.jar                         |Fruitful                      |fruitful                      |1.16.5-2.1.0        |DONE      |Manifest: NOSIGNATURE
		environmental-1.16.5-1.1.0.jar                    |Environmental                 |environmental                 |1.1.0               |DONE      |Manifest: NOSIGNATURE
		bamboo_blocks-1.16.5-3.0.0.jar                    |Bamboo Blocks                 |bamboo_blocks                 |3.0.0               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.16.5-3.0.1.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.1               |DONE      |Manifest: NOSIGNATURE
		Enhanced-Mushrooms-1.16.5-3.0.9.jar               |Enhanced Mushrooms            |enhanced_mushrooms            |1.16.5-3.0.9        |DONE      |Manifest: NOSIGNATURE
		Bayou-Blues-1.16.5-1.0.5.jar                      |Bayou Blues                   |bayou_blues                   |1.16.5-1.0.5        |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.6.0-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.6.0               |DONE      |Manifest: NOSIGNATURE
		Paxi-Forge-1.16.4-1.0.jar                         |Paxi                          |paxi                          |1.16.4-1.0          |DONE      |Manifest: NOSIGNATURE
		Kobolds-1.4.5.jar                                 |Kobolds                       |kobolds                       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Better-Badlands-1.16.5-2.0.3.jar                  |Better Badlands               |better_badlands               |1.16.5-2.0.3        |DONE      |Manifest: NOSIGNATURE
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.3.jar                        |Waystones                     |waystones                     |7.6.3               |DONE      |Manifest: NOSIGNATURE
		goldenhopper-1.2.0-1.16.3.jar                     |Golden Hopper                 |goldenhopper                  |1.2.0               |DONE      |Manifest: NOSIGNATURE
		Fallingleaves-1.16.3-1.1.1.jar                    |Falling Leaves                |fallingleaves                 |1.1.1               |DONE      |Manifest: NOSIGNATURE
		WeaponThrow-1.16.4-5.0.jar                        |Weapon Throw                  |weaponthrow                   |1.16.4-5.0          |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.2-mc1.16.5.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.2               |DONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.25.jar                               |Clumps                        |clumps                        |6.0.0.25            |DONE      |Manifest: NOSIGNATURE
		MoreEnchantments_MC_1.16.4_Vers.1.4.0.jar         |More Enchantments             |more_enchantments             |1.4.0               |DONE      |Manifest: NOSIGNATURE
		tumbleweed-1.16-0.4.9.jar                         |Tumbleweed                    |tumbleweed                    |1.16-0.4.9          |DONE      |Manifest: NOSIGNATURE
		configured-1.2.0-1.16.3.jar                       |Configured                    |configured                    |1.2.0               |DONE      |Manifest: NOSIGNATURE
		irregularchef-1.16.5-1.0.1.jar                    |The Irregular Chef            |irregularchef                 |1.16.5-1.0.1        |DONE      |Manifest: NOSIGNATURE
		stoneholm-1.2.2.jar                               |Stoneholm                     |stoneholm                     |1.2                 |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.16.5-2.3.2.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.2               |DONE      |Manifest: NOSIGNATURE
		curioofundying-forge-1.16.5-5.2.0.0.jar           |Curio of Undying              |curioofundying                |1.16.5-5.2.0.0      |DONE      |Manifest: NOSIGNATURE
		BadMobs-1.16.5-9.0.3.jar                          |BadMobs                       |badmobs                       |9.0.3               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		bedspreads-forge-1.16.5-5.1.0.2.jar               |Bedspreads                    |bedspreads                    |1.16.5-5.1.0.2      |DONE      |Manifest: NOSIGNATURE
		catalogue-1.3.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.3.0               |DONE      |Manifest: NOSIGNATURE
		Wandering-Bag-1.16.5-1.0.2.jar                    |Wandering Bag                 |wandering_bag                 |1.0.2               |DONE      |Manifest: NOSIGNATURE
		crumbs-forge-1.0.7.jar                            |Crumbs                        |crumbs                        |1.0.7               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |DONE      |Manifest: NOSIGNATURE
		TravelersTitles-1.16.4-1.5.jar                    |Traveler's Titles             |travelerstitles               |1.16.4-1.5          |DONE      |Manifest: NOSIGNATURE
		castle_dungeons-2.6-1.16.5-forge.jar              |Castle Dungeons               |castle_dungeons               |2.6                 |DONE      |Manifest: NOSIGNATURE
		OffHandCombat-1.16.3-3.2.0.3.jar                  |Off Hand Combat               |offhandcombat                 |1.16.3-3.2.0.3      |DONE      |Manifest: c9:84:cd:eb:27:ac:0d:ad:8c:55:6f:d6:5f:19:f2:c8:63:2a:b0:bd:3b:d0:b6:df:fd:9f:de:9f:9d:e8:7c:68
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		selene-1.16.5-1.7.jar                             |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		antiqueatlas-6.0.1-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.0.1-forge-mc1.16.5|DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.47-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.47              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		cavebiomeapi-1.16.5-1.3.7.jar                     |CaveBiomeAPI                  |cavebiomeapi                  |1.3.7               |DONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |DONE      |Manifest: NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.12.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.12              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |Manifest: NOSIGNATURE
		nohostilesaroundcampfire_1.16.5-3.6.jar           |No Hostiles Around Campfire   |nohostilesaroundcampfire      |3.6                 |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		Abundance-1.16.5-1.0.5.jar                        |Abundance                     |abundance                     |1.16.5-1.0.5        |DONE      |Manifest: NOSIGNATURE
		EntityCulling-1.16.5-2.1.6.jar                    |Entity Culling                |entity_culling                |2.1.6               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE
		atmospheric-1.16.5-3.1.0.jar                      |Atmospheric                   |atmospheric                   |3.1.0               |DONE      |Manifest: NOSIGNATURE
		jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |DONE      |Manifest: NOSIGNATURE
		Pillagers-1.16.5-3.0.1.jar                        |Pillagers                     |pillagers                     |3.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Iceberg-1.16.5-1.0.4.jar                          |Iceberg                       |iceberg                       |1.0.4               |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.4.jar                           |Flywheel                      |flywheel                      |1.16-0.2.4          |DONE      |Manifest: NOSIGNATURE
		ffenchants-1.16.5-1.4.1.jar                       |FlashFyre's Enchantments      |ffenchants                    |1.16.5-1.4.1        |DONE      |Manifest: NOSIGNATURE
		savageandravage-1.16.5-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |DONE      |Manifest: NOSIGNATURE
		autumnity-1.16.5-2.1.1.jar                        |Autumnity                     |autumnity                     |2.1.1               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-316.jar                                |Quark                         |quark                         |r2.4-316            |DONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.16.5-1.2.0.jar                |Abnormals Delight             |abnormals_delight             |1.2.0               |DONE      |Manifest: NOSIGNATURE
		copperpot-1.16.5-1.1.2.jar                        |Copper Pot                    |copperpot                     |1.16.5-1.1.2        |DONE      |Manifest: NOSIGNATURE
		sit-1.16.5-v1.3.1.jar                             |Sit                           |sit                           |v1.3.1              |DONE      |Manifest: NOSIGNATURE
		direbats-1.1.1+1.16.5-forge.jar                   |Direbats                      |direbats                      |1.1.1+1.16.5-forge  |DONE      |Manifest: NOSIGNATURE
		evilwanderingtrader-1.2.jar                       |Evil Wandering Trader         |evilwanderingtrader           |1.2                 |DONE      |Manifest: NOSIGNATURE
		CosyCommodities-1.16.5_1.2.jar                    |Cosy Commodities              |cosycommodities               |1.16.5_1.2          |DONE      |Manifest: NOSIGNATURE
		fancymenu_2.2.2-2_MC_1.16.2-1.16.5.jar            |FancyMenu                     |fancymenu                     |2.2.2               |DONE      |Manifest: NOSIGNATURE
		drippyloadingscreen_1.1.1_MC_1.16.2-1.16.5.jar    |Drippy Loading Screen         |drippyloadingscreen           |1.1.1               |DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.16.4-4.4.0.jar                      |FastFurnace                   |fastfurnace                   |4.4.0               |DONE      |Manifest: NOSIGNATURE
		workshopsofdoom-1.16.4-1.1.0.1.jar                |Workshops of Doom             |workshopsofdoom               |1.1.0.1             |DONE      |Manifest: NOSIGNATURE
		HunterIllager-1.16.5-1.4.0.jar                    |Hunter Illager                |hunterillager                 |1.16.5-1.4.0        |DONE      |Manifest: NOSIGNATURE
		illagersweararmor-1.0.5.jar                       |Illagers Wear Armor           |illagersweararmor             |1.0.5               |DONE      |Manifest: NOSIGNATURE
		nethers_delight-2.1.jar                           |Nethers Delight               |nethers_delight               |2.1                 |DONE      |Manifest: NOSIGNATURE
		cobbler-1.6.1.jar                                 |Shulkers Faithful Factories   |cobbler                       |1.6.1               |DONE      |Manifest: NOSIGNATURE
		[BETA]dannys_expansion1.16.5-1.0.9.1.jar          |Danny's Expansion             |dannys_expansion              |1.0.9               |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.0.6-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.6               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		enhancedcelestials-2.0.8-1.16.5.jar               |Enhanced Celestials           |enhancedcelestials            |2.0.8-1.16.5        |DONE      |Manifest: NOSIGNATURE
		FriendlyFire-1.16.5-7.0.2.jar                     |FriendlyFire                  |friendlyfire                  |7.0.2               |DONE      |Manifest: NOSIGNATURE
		bettergolem-1.16.5-0.2.0.jar                      |Better Golem                  |bettergolem                   |1.16.5-0.2.0        |DONE      |Manifest: NOSIGNATURE
		enchantingbooks-1.2.2.jar                         |Enchanting Books              |enchantingbooks               |1.2.2               |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.10.jar                        |Valhelsia Core                |valhelsia_core                |16.0.10             |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.5.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.5        |DONE      |Manifest: NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |DONE      |Manifest: NOSIGNATURE
		farmersreplant-1.16.5-1.0.jar                     |Farmers Replant               |farmersreplant                |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		DefaultOptions_1.16.5-12.2.1.jar                  |Default Options               |defaultoptions                |12.2.1              |DONE      |Manifest: NOSIGNATURE

**Comment by frqnny** [comment]
Do Pillager Outpost have pillagers? since this isn't an issue on my mod, I'm betting.

**Comment by GauntAndreX8** [comment]
I did some testing and no I think it’s your mod because pillagers are spawning in the pillage outpost took long cause I was on lunch that’s why

**Comment by frqnny** [comment]
i think its a compat issue since I've made sure it works outside of dev (with mostructures on its own)

**Comment by GauntAndreX8** [comment]
Oh well can it be fixed?
