### ISSUE TITLE
[Worldgen] Mod Preventing Silent's Mechanisms Oil Deposits Generation

### ISSUE THREAD

**Issue by Seikikai** [frqnny/mostructures-forge#5]
This Mod Is Preventing That Oil Blocks From [Silent's Mechanisms](https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms) Generate Naturally.

This Problem Was Tested Using A X-Ray Mod And Multiples Seeds. Also A Specific Seed [-9214212490253464253] With A Specific Location Were Used To Confirm The Problem.

Test Without The Mod:
![ScreenA](https://user-images.githubusercontent.com/54079357/139332677-70d947ed-c91d-47c8-9ba8-214389ed1514.png)
Test With The Mod:
![ScreenB](https://user-images.githubusercontent.com/54079357/139332683-66af270e-2818-45fc-9101-d51e0e1bc7a0.png)

**Comment by frqnny** [comment]
Seikikki i have no idea what I'm looking at so please explain and bring better evidence since it's not me causing it. otherwise I'm closing this
